global:
  name: Server
  motd: A Minecraft Server
  ip: 0.0.0.0
  startport: 25566
  defaultapp: vanilla-latest
  autoupdate:
    servers: true
    vanilla: true
    snapshot: true
    spigot: false
    bungeecord: true
  server-icons: true
  defaulticon: server-icon
bungeecord:
  bungeecord: true
  proxybypass: false
  version: 1105
  port: 25565
servers:
  default:
    mode: individual
    default:
      app: default
      defaultmap: Survival
      icon: default
      plugins:
      - PermissionsEx
      - Multiverse-Core
      maps:
      - world
eula: true
installed:
  apps: []
  plugins: []
  maps: []